
services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8081:8081
    environment:
     # - DATABASE_URL=mysql://avnadmin:AVNS_QkPkFbpLkTB8cco87t7@crm-mysql-crm-9786.a.aivencloud.com:27107/defaultdb?ssl-mode=REQUIRED # Aiven db
      - DATABASE_URL=mysql://root:AVNS_QkPkFbpLkTB8cco87t7@db:3306 # Docker mysql db
      - BACKEND_SERVER_ADDRESS=0.0.0.0
      - BACKEND_SERVER_PORT=8081
      - BACKEND_JWT_SECRET=090b64b0153738a2f6baf742b1b7a16f
      - BACKEND_HASH_SECRET=5693afd53dcbb16709c3c76d193061e3
      
    restart: always
    depends_on:
      db:
        condition: service_healthy
  
  db:
    container_name: mysql-db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: AVNS_QkPkFbpLkTB8cco87t7
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  nginx:
    container_name: nginx-proxy
    build:
      context: .
      dockerfile: nginx-proxy/Dockerfile
    restart: always
    ports: 
      - 80:80
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - server
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro

  #certbot:
  #  image: certbot/certbot:latest
  #  volumes:
  #    - ./certbot/www/:/var/www/certbot/:rw

