interface Client {
    crmUuid: string,
    uuid: string,
    firstName: string | null,
    lastName: string | null,
    dateOfBirth: string | null,
    email: string,
    address: string | null,
    zipCode: string | null,
    city: string | null,
    country: string | null,
    company: string | null,
    phoneNumber: string | null,
    newsLetter: boolean,
    added: string,
    updated: string,
    note: string,
}
