interface Employee {
    crmUuid: string,
    uuid: string,
    userUuid: string | null,
    firstName: string | null,
    lastName: string | null,
    dateOfBirth: string | null,
    ssn: string | null,
    address: string | null,
    zipCode: string | null,
    city: string | null,
    country: string | null,
    phoneNumber: string | null,
    role: string | null,
    drivingLicenseClass: string | null,
    periodOfValidity: string | null,
    bankNumber: string | null,
    clearingNumber: string | null,
    bankName: string | null,
    email: string | null,
    employmentType: string | null,
    accessLevel: string | null,
    added: string,
    updated: string
}

